-- 코드를 입력하세요
-- USED_GOODS_REPLY-> TBL2 / USED_GOODS_BOARD-> TBL1 / 
SELECT 
 TBL1.TITLE,
 TBL1.BOARD_ID,
 TBL2.REPLY_ID,
 TBL2.WRITER_ID,
 TBL2.CONTENTS,
 DATE_FORMAT(TBL2.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS TBL1
JOIN USED_GOODS_REPLY AS TBL2 ON TBL1.BOARD_ID = TBL2.BOARD_ID
WHERE TBL1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY TBL2.CREATED_DATE ASC, TBL1.TITLE ASC